// src/layout/layout.index.tsx
import AppLayout from './layout.app'
import { ElDrawer } from 'element-plus'
import DrawerThemeConfiger from './PageConfig/config.theme.vue'
import DrawerLayoutConfiger from './PageConfig/config.layout.vue'

import { UseLayoutStore } from '@/store/layout/layout.index'
import { storeToRefs } from 'pinia'
const Layout = () => {
  const layoutStore = UseLayoutStore()
  const AppContainer = AppLayout[layoutStore.layoutMode]
  const showDrawer = () => {
    layoutStore.toggleDrawerDisplay(true)
  }
  const { drawer } = storeToRefs(layoutStore)
  return (
    <>
      <AppContainer showDrawer={showDrawer}></AppContainer>
      <ElDrawer
        modelValue={drawer.value}
        onUpdate:modelValue={value => layoutStore.toggleDrawerDisplay(value)}
        title="系统页面配置">
        <DrawerThemeConfiger />
        <DrawerLayoutConfiger />
      </ElDrawer>
    </>
  )
}


export default Layout

// src/layout/layout.index.vue
<script setup lang='ts'>
import FullPageLayout from './layout.fullPageLayout.vue'
import NoSidebarLayout from './layout.noSidebarLayout.vue'

import DrawerThemeConfiger from './PageConfig/config.theme.vue'
import DrawerLayoutConfiger from './PageConfig/config.layout.vue'

import { UseLayoutStore, LayoutEnum } from '@/store/layout/layout.index';
import { storeToRefs } from 'pinia';
const layoutStore = UseLayoutStore()
const { layoutMode } = storeToRefs(layoutStore)
const AppContainer = computed(() => {
  return {
    [LayoutEnum.FullPageLayout]: FullPageLayout,
    [LayoutEnum.NoSidebarLayout]: NoSidebarLayout
  }[layoutMode.value]
})
const showDrawer = () => {
  layoutStore.toggleDrawerDisplay(true)
}
</script>

<template>
  <component :is="AppContainer" @showDrawer="showDrawer"></component>
  <!-- <el-drawer :modelValue="layoutStore.layoutMode" @onUpdate:modelValue='(value: boolean) => layoutStore.toggleDrawerDisplay(value)' -->
  <el-drawer :modelValue="layoutStore.drawer"
    @update:modelValue='(value: boolean) => layoutStore.toggleDrawerDisplay(value)' title="系统页面配置">
    <DrawerThemeConfiger />
    <DrawerLayoutConfiger />
  </el-drawer>
</template>

<style lang='scss' scoped>
</style>
